# Generated by Django 4.1.7 on 2023-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=20, verbose_name='name of field one')),
                ('date', models.DateField(verbose_name='Date one')),
                ('datetime', models.DateTimeField(verbose_name='Date and Time')),
                ('check_point', models.BooleanField(verbose_name='Check point')),
                ('integer', models.IntegerField(verbose_name='Number')),
                ('choice', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], verbose_name='Choice')),
            ],
        ),
    ]
